### PR TITLE
Bugfix dependency ClassMetaData

### PR DESCRIPTION
**Pull request by Tilotiti**

### CODE REVIEW

**Comment by liarco** [comment]
I'm stuck with a project using Symfony `5.1` because of the bug fixed by this PR.

**Comment by webda2l** [comment]
Hello,
Not the right solution IMO, try the new release https://github.com/a2lix/AutoFormBundle/releases/tag/0.3.2

**Comment by liarco** [comment]
I confirm the new release is working. Thank you very much, I'm gonna take a look to your commits to see the different approach.

**Comment by webda2l** [comment]
@liarco fine :)
I close this PR.

**Pull request closed without merging**
